version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
    pre_build:
        commands:
            - echo Installing source NPM dependencies...
            - npm install -g @angular/cli
            - npm install
    build:
        commands:
            - echo Building the Admin Panel code...
            - npm run build:prod
artifacts:
    base-directory: $CODEBUILD_SRC_DIR/dist
    files:
        - '**/*'
